version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

