version: "3.8"

services:
  web: 
    image: rlmuthukumar/nodejs-mysql-ci-cd:$BUILD_NUMBER
    container_name: nodejs-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=testdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=testdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
